apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodic-scan
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scanning
            image: scanner:dev
            imagePullPolicy: Never
            args:
              - "127.0.0.1"
          restartPolicy: OnFailure
