#!/usr/bin/env python3

import socket
import ipaddress
import sys


PORT_MAX = 65000

def generate_ips(input_string):
    return [str(ip) for ip in ipaddress.IPv4Network(input_string)]

def check_tcp_port(ip, port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    result = sock.connect_ex(('127.0.0.1',80))
    sock.close()
    return not result

def check_udp_port(host, port):
    udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    udp_socket.settimeout(1)
    try:
        udp_socket.sendto('ping'.encode(), (host, port))
        udp_socket.recvfrom(1024)
    except socket.timeout:
        udp_socket.close()
        print(1)
        return 1
    udp_socket.close()
    return 0  # 0 == Port is open
    

def scan(ips):
    """
        Check all ips and all ports for TCP.
        If not found check for UDP.
        Printout results
    """
    for ip in ips:
        print(f"{ ip }:")
        for port in range(PORT_MAX):
            if check_tcp_port(ip, port):
                print(f"* {port}/tcp open")
            elif check_udp_port(ip, port) == 0:
                print(f"* {port}/udp open")
            else:
                print(f"* {port} closed")


if __name__ == "__main__":
    all_ips = generate_ips(sys.argv[1])
    scan(all_ips)